# Generated by Django 4.1.4 on 2023-01-20 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('nome', models.CharField(max_length=250, unique=True)),
                ('numero', models.IntegerField(unique=True, verbose_name='Número')),
                ('bloco', models.CharField(max_length=10, verbose_name='Bloco')),
                ('descricao', models.TextField(max_length=100, verbose_name='Descrição')),
                ('capacidade', models.IntegerField(verbose_name='Capacidade')),
                ('laboratorio', models.BooleanField(default=False, verbose_name='É laboratório?')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('descricao', models.TextField(blank=True, max_length=100, verbose_name='Descrição')),
                ('data', models.DateField(blank='False', null='False')),
                ('horario', models.CharField(choices=[('07:00 - 07:45', '07:00 - 07:45'), ('07:45 - 08:30', '07:45 - 08:30'), ('08:50 - 09:35', '08:50 - 09:35'), ('09:35 - 10:20', '09:35 - 10:20'), ('10:30 - 11:15', '10:30 - 11:15'), ('11:15 - 12:00', '11:15 - 12:00'), ('13:00 - 13:45', '13:00 - 13:45'), ('13:45 - 14:30', '13:45 - 14:30'), ('14:50 - 15:35', '14:50 - 15:35'), ('15:35 - 16:20', '15:35 - 16:20'), ('16:30 - 17:15', '16:30 - 17:15'), ('17:15 - 18:00', '17:15 - 18:00'), ('19:00 - 19:45', '19:00 - 19:45'), ('19:45 - 20:30', '19:45 - 20:30'), ('20:40 - 21:25', '20:40 - 21:25'), ('21:25 - 22:10', '21:25 - 22:10')], max_length=15)),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.sala')),
            ],
        ),
    ]
