# Generated by Django 4.1.4 on 2023-02-07 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='nome',
        ),
    ]
