# Generated by Django 4.1.4 on 2023-01-20 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='nome',
        ),
    ]
