# Generated by Django 4.1.4 on 2023-01-23 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0003_remove_reserva_nome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='usuario',
        ),
    ]
