# Generated by Django 4.1.4 on 2023-01-30 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0004_remove_reserva_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sala',
            name='bloco',
            field=models.CharField(choices=[('Bloco 02', 'Bloco 02'), ('Bloco 03', 'Bloco 03')], max_length=8, verbose_name='Bloco'),
        ),
        migrations.AlterField(
            model_name='sala',
            name='tipo',
            field=models.CharField(choices=[('Alimentos', 'Alimentos'), ('Apicultura', 'Apicultura'), ('Informática', 'Informática'), ('Quimíca', 'Quimíca')], max_length=13, verbose_name='Tipo'),
        ),
    ]
