# Generated by Django 4.1.4 on 2023-01-25 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0006_alter_reserva_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sala',
            name='descricao',
            field=models.TextField(default=False, max_length=100, verbose_name='Descrição'),
        ),
    ]
