# Generated by Django 4.1.4 on 2023-01-25 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0007_alter_sala_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sala',
            name='descricao',
            field=models.TextField(blank=True, max_length=100, verbose_name='Descrição'),
        ),
    ]
