# Generated by Django 4.1.4 on 2023-01-11 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='bloco',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='capacidade',
        ),
        migrations.AlterField(
            model_name='reserva',
            name='descricao',
            field=models.TextField(blank=True, max_length=100, verbose_name='Descrição'),
        ),
    ]
