# Generated by Django 4.1.4 on 2023-01-16 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0003_sala_laboratorio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='usuario',
        ),
    ]
