# Generated by Django 4.1.3 on 2022-12-03 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Labs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=200, verbose_name='Descrição')),
            ],
        ),
        migrations.CreateModel(
            name='Salas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('numero', models.IntegerField(verbose_name='Número')),
                ('descricao', models.CharField(max_length=200, verbose_name='Descrição')),
                ('campo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.labs')),
            ],
        ),
    ]
